openapi: 3.0.3
info:
  title: Task Manager API
  description: API para la gestión de tareas del curso Diseño de APIs REST
  version: 1.0.0 
  contact:
    name: Equipo del curso
    url: soporte@taskmanager.dev
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:3000/v1
    description: Servidor local de desarrollo
  - url: https://staging.api.taskmanager.dev/v1
    description: Servidor de staging
paths: {}

tags:
  - name: Tasks
    description: Operaciones relacionadas con la gestión de tareas